version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5556:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
